backend:
  name: github
  repo: rebeccabarenfeld/newlp
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "avocat"
    label: "Mon Cabinet"
    files:
      - label: "Informations générales"
        name: "general"
        file: "_data/general.json"
        fields:
          - {label: "Nom du cabinet", name: "nom_cabinet", widget: "string"}
          - {label: "Nom de l'avocat", name: "nom_avocat", widget: "string"}
          - {label: "Slogan", name: "slogan", widget: "string"}
          - {label: "Téléphone", name: "telephone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Adresse", name: "adresse", widget: "string"}
          - {label: "Description bio", name: "bio", widget: "text"}
